### ISSUE TITLE
Return unspent raffle wins to the pool

### ISSUE THREAD

**Issue by abrkn** [abrkn/shilly#23]
7 days? Maybe even less. It's about being active. Installing a wallet and sweeping takes < 1 hour

**Comment by mittremblay** [comment]
Agreed, if some people never check discord, it doesnt benefit the current users as much. Consider adding this statement to the description of Shilly when winning as well, that if funds are not claimed within X amount of time, it will return to the pool for future lotteries.

**Comment by mittremblay** [comment]
I suggest completing issue #25 before completing this issue.
