### ISSUE TITLE
Limit Shillys participants?

### ISSUE THREAD

**Issue by mittremblay** [abrkn/shilly#50]
If it's possible to limit Shillys participants of the lottery to only people who have posted once in a chat room? Or a similar type audience? I can't help but thing there are tons of people in discord who have never used it and just get tips, or maybe that's their intention? Ive never won in one time in weeks.

**Comment by abrkn** [comment]
Wouldn't this incentivize people to spam?

**Comment by mittremblay** [comment]
Very good point, perhaps some other mechanism. 

How does Discord determine if someone is "online"?
perhaps that is already enough which would make this issue pointless. This issue was written assuming that people would be able to join discord and technically never be considered offline, but I see that's not the case since there's only 100 or so people online normally.

I don't think this issue is viable anymore since the creation of it since the "online" feature does what i intended, so I will respectably close it.
