### ISSUE TITLE
Idea: Group !roll

### ISSUE THREAD

**Issue by mittremblay** [abrkn/shilly#67]
A !roll command that would pay out hourly or so. Me and another user could roll (shilly would mark each amount the user put in and pool it together) if a user wins the roll, they could get 66% of that hours amount while house gets 33%, or they could get 100% if they win and 0% if they lose, like how !roll is now.

Bigger payouts and more games like this would encourage daily use of discord and social interaction down to the hour.

**Comment by abrkn** [comment]
This one's too difficult to implement. If anyone else wants to, go ahead
