### ISSUE TITLE
$0.01!Roll error?

### ISSUE THREAD

**Issue by mittremblay** [abrkn/shilly#68]
It may be an error (very small one) but !roll $0.01 And if you win, it says you won less than 1 cent. While !roll $0.02 wins you exactly 2 cents.

**Comment by abrkn** [comment]
That's a weird one, because the check is:

```javascript
exports.formatUsd = _ => {
  if (+_ < 0.01) {
    return '`< $0.01`';
  }

  return '`$' + numeral(_.toString()).format('0,0.00') + '`';
};
```

Any ideas?

**Comment by mittremblay** [comment]
The price likely changed between the !roll command being received and the house processing the payout and resulted in a lower amount, I don't believe there is any way to resolve this as it's due to normal price fluctuations.
