### ISSUE TITLE
Basic Documentation

### ISSUE THREAD

**Issue by A-Chewy-1** [abrkn/shilly#74]
Write up some basic documentation to help Discord Server owners to deploy shilly on their own servers.

**Comment by leon-yum** [comment]
Yes please! I like tipping people with Bitcoin Cash and would love to do that in my other Discord channels as well :)

**Comment by NeVroe** [comment]
I could create an VMware ovf-file with an ubuntu instance with all prereqs if anyone is interested?

**Comment by A-Chewy-1** [comment]
Just documentation on getting the bot running please. I'm already running a VM for my node.

**Comment by leon-yum** [comment]
Could you add the VMware steps as well? Or link to what you are doing and how to use that instance?

**Comment by zander** [comment]
This may be  good place to start:

https://discord.js.org/#/docs/main/stable/general/welcome
