### ISSUE TITLE
A channel that posts about new submissions to https://acceptbitcoin.cash/

### ISSUE THREAD

**Issue by abrkn** [abrkn/shilly#9]
> A channel that posts about new submissions to https://acceptbitcoin.cash/ - the site that monitors new stores adding BCH as a payment method.
>
> Can link it up directly with https://github.com/acceptbitcoincash/acceptbitcoincash where new submissions to the site are added?

**Comment by mittremblay** [comment]
Consider adding a counter than counts all of these submissions, and consider a daily or weekly post saying how many new stores have been accepted that week (daily may end up being so small it's insignificant)
